export const STRUCTURED_MAX_ROWS = 50_000;
export const STRUCTURED_MAX_COLUMNS = 100;
export const STRUCTURED_MAX_CELLS = 2_000_000;
export const STRUCTURED_TOP_N_MAX = 100;
export const STRUCTURED_EVIDENCE_MAX = 100;
export const STRUCTURED_TIE_SCAN_MAX = 1_000;
export const STRUCTURED_QUERY_TIMEOUT_MS = 10_000;
