events {}

http {

    upstream embed {
        server tei-embed:80;
    }

    upstream rerank {
        server tei-rerank:80;
    }

    server {
        listen 80;

        # redirect HTTPS (nếu có cert)
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;

        ssl_certificate     /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        # EMBED API
        location /embed {
            proxy_pass http://embed/embed;
        }

        # RERANK API
        location /rerank {
            proxy_pass http://rerank/rerank;
        }

        # basic protection (optional)
        client_max_body_size 2m;
    }
}