[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name              tail
    Tag               nodejs.app
    Path              /var/log/node-app/app.log
    Parser            nodejs_json
    DB                /fluent-bit/state/nodejs-app.db
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Refresh_Interval  1
    Read_From_Head    On

[FILTER]
    Name    modify
    Match   nodejs.app
    Add     log_source fluent-bit

[OUTPUT]
    Name            es
    Match           nodejs.app
    Host            elasticsearch
    Port            9200
    Index           nodejs-logs
    Logstash_Format On
    Logstash_Prefix nodejs-logs
    Suppress_Type_Name On
    Replace_Dots    On
    Retry_Limit     False

